version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-card
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: card_db
      MYSQL_USER: carduser
      MYSQL_PASSWORD: cardpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  card-api:
    build: .
    container_name: card-api
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data: