spring:
  config:
    activate:
      on-profile: local
  server:
    port: 8081
  datasource:
    url: jdbc:mysql://localhost:3306/card_db?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: rootpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
    org.springframework: INFO
    com.example.cardapi: DEBUG

